secrets:

  config-server-secrets:
    ENCRYPT_KEY: my-very-secure-encrypt-key
    SPRING_SECURITY_USER_NAME: dev-usr
    SPRING_SECURITY_USER_PASSWORD: dev-pwd

  config-client-credentials:
    CONFIG_SERVER_USR: dev-usr
    CONFIG_SERVER_PWD: dev-pwd

mysql:
  env:
    MYSQL_ROOT_PASSWORD: write
    MYSQL_DATABASE: own
    MYSQL_USER: your
    MYSQL_PASSWORD: mysql profile

config-server:
  envFromSecretRefs:
    - config-server-secrets

gateway:
  envFromSecretRefs:
    - config-client-credentials

model:
  envFromSecretRefs:
    - config-client-credentials

model-management:
  envFromSecretRefs:
    - config-client-credentials
