apiVersion: v2
appVersion: "1.0"
description: A Helm chart for QA or Production environment
name: prod-env
version: 1.0.0

dependencies:

  - name: common
    version: 1.0.0
    repository: file://../../common

  - name: config-server
    version: 1.0.0
    repository: file://../../components/config-server

  - name: gateway
    version: 1.0.0
    repository: file://../../components/gateway
